### ISSUE TITLE
Frames not generating properly.

### ISSUE THREAD

**Issue by bshahTibicle** [josephrocca/getVideoFrames.js#3]
Hello @josephrocca,

I have integrate **mod.js** in my Web application.

If i was select video of **10 minutes** & 24fps then  (60*10*24) 14400 frames need to generate. But i **got only 3000 frames**.
on
"**onFrame(frame:any) {}**" function of "**getVideoFrames({})**", i get only 3000 frames.

so i have checked **code in mod.js**,
below function **called 15 times**. and chunk count match near about 14400. 
**async #onSamples(track_id, ref, samples) { }** 

Can you please check this? how can i get all frames in "onFrame(frame:any) {}" function?

**Comment by vlasakjiri** [comment]
I have encourtered similar issue, where even a short video (5-10s) does not generate all the samples that are specified in the info.VideoTracks.num_samples property.

**Comment by josephrocca** [comment]
I unfortunately haven't looked at this code in ages. You are currently better positioned to solve this - if you do please open a pull request to help others who are having similar issues

**Comment by pedrobroese** [comment]
> I have encourtered similar issue, where even a short video (5-10s) does not generate all the samples that are specified in the info.VideoTracks.num_samples property.

Take a look at this issue: https://github.com/gpac/mp4box.js/issues/243  With the code from there and mp4Box you'll be able to retrieve all frames from mp4 file in a reliable manner.

**Comment by josephrocca** [comment]
Okay this should be fixed now - I've just tested it with [this video](https://w3c.github.io/webcodecs/samples/data/bbb_video_avc_frag.mp4) and it gives the correct number of frames. If you're still having troubles with v0.0.9, then please open another issue and provide an example video to use in this demo: https://jsbin.com/gehaqureca/edit?html,output
